version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - actix
  - chrono
  - Datelike
  - dioxus
  - eframe
  - egui
  - rustup
  - serde
  - slint
  - Timelike
  - unmultiplied
ignoreWords: []
import: []
